module top (
    output wire [7:0] pmod,
    output wire       fan_en_b
);

    // Outputs from block design
    wire [7:0] pmod_gpio_o;   // AXI GPIO, PMOD connector J2
    wire [0:0] fan_en_b_bd;   // TTC0 wave_out[0] via EMIO (active-low fan enable)

    // PMOD J2: pmod[0..3] = top row (pins 1-4), pmod[4..7] = bottom row (pins 7-10)
    assign pmod = pmod_gpio_o;

    // Fan (A12): HIGH = fan OFF, LOW/idle = fan ON (failsafe)
    assign fan_en_b = fan_en_b_bd[0];

    // Instantiate the Zynq BD wrapper (generated by Vivado from create_bd.tcl)
    zynq_bd_wrapper ps_block (
        .pmod_gpio_o(pmod_gpio_o),
        .fan_en_b   (fan_en_b_bd)
    );

endmodule
