module top (
    output wire [3:0] leds
);

    // AXI GPIO output from block design (4-bit, active-high LEDs)
    wire [3:0] gpio_io_o_0;

    // Connect GPIO outputs directly to carrier card LEDs (DS5–DS8, active-high)
    assign leds = gpio_io_o_0;

    // Instantiate the Zynq BD wrapper (generated by Vivado from create_bd.tcl)
    zynq_bd_wrapper ps_block (
        .gpio_io_o_0(gpio_io_o_0)
    );

endmodule
