module top (
    output wire [3:0] leds,
    output wire [7:0] pmod
);

    // AXI GPIO outputs from block design
    wire [3:0] gpio_io_o_0;   // 4-bit, active-high carrier LEDs
    wire [7:0] pmod_gpio_o;   // 8-bit, PMOD connector J2

    // Connect GPIO outputs directly to carrier card LEDs (DS5–DS8, active-high)
    assign leds = gpio_io_o_0;

    // PMOD J2: pmod[0..3] = top row (pins 1-4), pmod[4..7] = bottom row (pins 7-10)
    assign pmod = pmod_gpio_o;

    // Instantiate the Zynq BD wrapper (generated by Vivado from create_bd.tcl)
    zynq_bd_wrapper ps_block (
        .gpio_io_o_0(gpio_io_o_0),
        .pmod_gpio_o(pmod_gpio_o)
    );

endmodule
